### ISSUE TITLE
error about creating TFrecord file while running vica get_features 

### ISSUE THREAD

**Issue by qingpeng** [USDA-ARS-GBRU/vica#3]
Split into testing and training using sorted.fa file and succeeded.

python ~/Denovo35/vica/vica/vica_cli.py split -i /global/projectb/scratch/qpzhang/ViCA/sorted.fa --out /global/projectb/scratch/qpzhang/ViCA/second_run &

modified the config_default.yml to run minhash locally.

python ~/Denovo35/vica/vica/vica_cli.py get_features -i 2.fasta --out 2.fasta.tfrecord

last part of the vica.log:

Finding genes in sequence #4845 (5000 bp)...done!
Finding genes in sequence #4846 (5000 bp)...done!
Finding genes in sequence #4847 (5000 bp)...done!
Finding genes in sequence #4848 (5000 bp)...done!

2017-12-26 14:12:42 root         INFO     Wrote 4848 examples to the temporary file
2017-12-26 14:12:42 root         INFO     Processed Codon features in: 0:01:52.354231
2017-12-26 14:12:42 root         INFO     Writing data to the TFrecord file 2.fasta.tfrecord
2017-12-26 14:12:42 root         ERROR    vica get_features: While creating a TFrecord file the following exception occcured:
Traceback (most recent call last):
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 119, in run
    label=str(label), sort=True)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/tfrecord_maker.py", line 95, in convert_to_tfrecords
    tfrecordfile=tfrecordfile, label=label)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/tfrecord_maker.py", line 66, in csv_to_tfrecords
    tf.train.Feature(int64_list=tf.train.Int64List(value=[int(label)])),
ValueError: invalid literal for int() with base 10: 'None'
2017-12-26 14:12:42 root         ERROR    vica_cli.py: The following exception occured:
Traceback (most recent call last):
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 119, in run
    label=str(label), sort=True)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/tfrecord_maker.py", line 95, in convert_to_tfrecords
    tfrecordfile=tfrecordfile, label=label)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/tfrecord_maker.py", line 66, in csv_to_tfrecords
    tf.train.Feature(int64_list=tf.train.Int64List(value=[int(label)])),
ValueError: invalid literal for int() with base 10: 'None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/q/qpzhang/Denovo35/vica/vica/vica_cli.py", line 239, in main
    configpath=args.config)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 122, in run
    raise SystemExit(1)
SystemExit: 1

**Comment by arivers** [comment]
When running get_features you need to specify an integer using the ` --label` flag to represent the category of training data I usually use [0,1,2,3].  I'll make this a required flag for now and look into ways to make this automatic.

**Comment by qingpeng** [comment]
Thanks!

but while I tried to run it with minhashlocal option on , something wrong with the minhash feature extraction:


(vicaenv_denovo_35) qpzhang@denovo1:/global/projectb/scratch/qpzhang/ViCA> python ~/Denovo35/vica/vica/vica_cli.py get_features -i 2.fasta --out 2.fasta.tfrecord --label 2 --minhashlocal
08:41:09: INFO     Starting Vica: software for the indentification of highly divergent DNA and RNA viruses
08:41:09: INFO     Configuration data loaded from /global/u2/q/qpzhang/Denovo35/vica/vica/data/config_default.yml:
08:41:09: INFO     {'minhash': {'taxfilterlevel': 'genus', 'ref': '/global/projectb/sandbox/gaag/bbtools/refseq/current/taxa#.sketch', 'noncellular': {439488: 'ssRNA viruses', 35268: 'Retro-transcribing viruses', 29258: 'ssDNA viruses', 12877: 'Satellites', 39759: 'Deltavirus', 451344: 'unclassified archaeal viruses', 12884: 'Viroids', 686617: 'unassigned viruses', 1714266: 'Virus families not assigned to an order', 12429: 'unclassified viruses', 1910928: 'Genomoviridae', 35237: 'dsDNA viruses, no RNA stage', 1922347: 'unclassified RNA viruses', 552364: 'unclassified virophages', 12333: 'unclassified bacterial viruses', 35325: 'dsRNA viruses'}, 'server_url': 'https://refseq-sketch.jgi-psf.org/sketch', 'superkingdom': {2: 'Bacteria', 2759: 'Eukaryota', 12884: 'Viroids', 2157: 'Archaea', 10239: 'Viruses'}, 'blacklist': '/global/projectb/sandbox/gaag/bbtools/refseq/current/blacklist_refseq_species_300.sketch', 'nodesfile': 'phylum.txt', 'tree': '/global/projectb/sandbox/gaag/bbtools/tax/latest/tree.taxtree.gz', 'memory': None, 'taxfilter': '/global/projectb/scratch/qpzhang/ViCA/second_run/test/test_taxids.txt'}, 'train_eval': {'eval_batch_size': 512, 'model': 'DNNLogistic', 'epochs': 10, 'train_batch_size': 32, 'minhashlength': 267, 'codonlength': 177}, 'get_features': {'tempdir': None}, 'khmer_features': {'ksize': 5}, 'classifier': None, 'prodigal': {'codon_list': ['TTT', 'TCT', 'TAT', 'TGT', 'TTC', 'TCC', 'TAC', 'TGC', 'TTA', 'TCA', 'TAA', 'TGA', 'TTG', 'TCG', 'TAG', 'TGG', 'CTT', 'CCT', 'CAT', 'CGT', 'CTC', 'CCC', 'CAC', 'CGC', 'CTA', 'CCA', 'CAA', 'CGA', 'CTG', 'CCG', 'CAG', 'CGG', 'ATT', 'ACT', 'AAT', 'AGT', 'ATC', 'ACC', 'AAC', 'AGC', 'ATA', 'ACA', 'AAA', 'AGA', 'ATG', 'ACG', 'AAG', 'AGG', 'GTT', 'GCT', 'GAT', 'GGT', 'GTC', 'GCC', 'GAC', 'GGC', 'GTG', 'GCG', 'GAG', 'GGG']}}
08:41:09: INFO     temporary directory: /scratch/qpzhang/tmptklnjlfd
08:41:09: INFO     Extacting minhash signatures and identifying them locally
08:41:09: INFO     Using BBtools Comparesketch.sh to identify matching taxa in the local database /global/projectb/sandbox/gaag/bbtools/refseq/current/taxa#.sketch
08:41:09: ERROR    vica get_features: during minhash local feature selection the following exception occcured:
Traceback (most recent call last):
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 62, in run
    noncellular=config["minhash"]["noncellular"])
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 212, in minhashlocal
    memory=memory)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 74, in _compare_sketch
    sendsketchout = subprocess.run(options, stderr=subprocess.PIPE)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly
08:41:09: ERROR    vica_cli.py: The following exception occured:
Traceback (most recent call last):
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 62, in run
    noncellular=config["minhash"]["noncellular"])
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 212, in minhashlocal
    memory=memory)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 74, in _compare_sketch
    sendsketchout = subprocess.run(options, stderr=subprocess.PIPE)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/q/qpzhang/Denovo35/vica/vica/vica_cli.py", line 239, in main
    configpath=args.config)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 65, in run
    raise SystemExit(1)
SystemExit: 1

**Comment by qingpeng** [comment]
Thanks!

but while I tried to run it with minhashlocal option on, it seems that something is wrong with minhash exaction...



(vicaenv_denovo_35) qpzhang@denovo1:/global/projectb/scratch/qpzhang/ViCA/second_run/train> python ~/Denovo35/vica/vica/vica_cli.py get_features -i 2.fasta --out 2.fasta.tfrecord --label 2 --minhashlocal
09:10:36: INFO     Starting Vica: software for the indentification of highly divergent DNA and RNA viruses
09:10:36: INFO     Configuration data loaded from /global/u2/q/qpzhang/Denovo35/vica/vica/data/config_default.yml:
09:10:36: INFO     {'minhash': {'server_url': 'https://refseq-sketch.jgi-psf.org/sketch', 'nodesfile': 'phylum.txt', 'taxfilterlevel': 'genus', 'memory': None, 'ref': '/global/projectb/sandbox/gaag/bbtools/refseq/current/taxa#.sketch', 'superkingdom': {2: 'Bacteria', 2759: 'Eukaryota', 12884: 'Viroids', 2157: 'Archaea', 10239: 'Viruses'}, 'noncellular': {439488: 'ssRNA viruses', 35268: 'Retro-transcribing viruses', 29258: 'ssDNA viruses', 12877: 'Satellites', 39759: 'Deltavirus', 451344: 'unclassified archaeal viruses', 12884: 'Viroids', 686617: 'unassigned viruses', 1714266: 'Virus families not assigned to an order', 12429: 'unclassified viruses', 1910928: 'Genomoviridae', 35237: 'dsDNA viruses, no RNA stage', 1922347: 'unclassified RNA viruses', 552364: 'unclassified virophages', 12333: 'unclassified bacterial viruses', 35325: 'dsRNA viruses'}, 'tree': '/global/projectb/sandbox/gaag/bbtools/tax/latest/tree.taxtree.gz', 'blacklist': '/global/projectb/sandbox/gaag/bbtools/refseq/current/blacklist_refseq_species_300.sketch', 'taxfilter': '/global/projectb/scratch/qpzhang/ViCA/second_run/test/test_taxids.txt'}, 'get_features': {'tempdir': None}, 'prodigal': {'codon_list': ['TTT', 'TCT', 'TAT', 'TGT', 'TTC', 'TCC', 'TAC', 'TGC', 'TTA', 'TCA', 'TAA', 'TGA', 'TTG', 'TCG', 'TAG', 'TGG', 'CTT', 'CCT', 'CAT', 'CGT', 'CTC', 'CCC', 'CAC', 'CGC', 'CTA', 'CCA', 'CAA', 'CGA', 'CTG', 'CCG', 'CAG', 'CGG', 'ATT', 'ACT', 'AAT', 'AGT', 'ATC', 'ACC', 'AAC', 'AGC', 'ATA', 'ACA', 'AAA', 'AGA', 'ATG', 'ACG', 'AAG', 'AGG', 'GTT', 'GCT', 'GAT', 'GGT', 'GTC', 'GCC', 'GAC', 'GGC', 'GTG', 'GCG', 'GAG', 'GGG']}, 'khmer_features': {'ksize': 5}, 'train_eval': {'codonlength': 177, 'eval_batch_size': 512, 'train_batch_size': 32, 'epochs': 10, 'model': 'DNNLogistic', 'minhashlength': 267}, 'classifier': None}
09:10:36: INFO     temporary directory: /scratch/qpzhang/tmpclas1mmo
09:10:36: INFO     Extacting minhash signatures and identifying them locally
09:10:36: INFO     Using BBtools Comparesketch.sh to identify matching taxa in the local database /global/projectb/sandbox/gaag/bbtools/refseq/current/taxa#.sketch
09:10:36: ERROR    vica get_features: during minhash local feature selection the following exception occcured:
Traceback (most recent call last):
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 62, in run
    noncellular=config["minhash"]["noncellular"])
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 212, in minhashlocal
    memory=memory)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 74, in _compare_sketch
    sendsketchout = subprocess.run(options, stderr=subprocess.PIPE)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly
09:10:36: ERROR    vica_cli.py: The following exception occured:
Traceback (most recent call last):
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 62, in run
    noncellular=config["minhash"]["noncellular"])
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 212, in minhashlocal
    memory=memory)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/minhash.py", line 74, in _compare_sketch
    sendsketchout = subprocess.run(options, stderr=subprocess.PIPE)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/global/homes/q/qpzhang/.conda/envs/vicaenv_denovo_35/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/q/qpzhang/Denovo35/vica/vica/vica_cli.py", line 239, in main
    configpath=args.config)
  File "/global/u2/q/qpzhang/Denovo35/vica/vica/get_features.py", line 65, in run
    raise SystemExit(1)
SystemExit: 1

**Comment by arivers** [comment]
You needed to specify the memory option in the config file.  I just changed vica to make it optional.
